// Code generated by protoc-gen-go. DO NOT EDIT.
// source: sum.proto

/*
Package sum is a generated protocol buffer package.

It is generated from these files:
	sum.proto

It has these top-level messages:
	Request
	SumRequest
	SumResponse
	PrimeNumberRequest
	PrimeNumberResponse
	ComputeAverageRequest
	ComputeAverageResponse
*/
package sum

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Request struct {
	FirstNumber  int64 `protobuf:"varint,1,opt,name=first_number,json=firstNumber" json:"first_number,omitempty"`
	SecondNumber int64 `protobuf:"varint,2,opt,name=second_number,json=secondNumber" json:"second_number,omitempty"`
}

func (m *Request) Reset()                    { *m = Request{} }
func (m *Request) String() string            { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()               {}
func (*Request) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Request) GetFirstNumber() int64 {
	if m != nil {
		return m.FirstNumber
	}
	return 0
}

func (m *Request) GetSecondNumber() int64 {
	if m != nil {
		return m.SecondNumber
	}
	return 0
}

type SumRequest struct {
	Req *Request `protobuf:"bytes,1,opt,name=req" json:"req,omitempty"`
}

func (m *SumRequest) Reset()                    { *m = SumRequest{} }
func (m *SumRequest) String() string            { return proto.CompactTextString(m) }
func (*SumRequest) ProtoMessage()               {}
func (*SumRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *SumRequest) GetReq() *Request {
	if m != nil {
		return m.Req
	}
	return nil
}

type SumResponse struct {
	Response int64 `protobuf:"varint,1,opt,name=response" json:"response,omitempty"`
}

func (m *SumResponse) Reset()                    { *m = SumResponse{} }
func (m *SumResponse) String() string            { return proto.CompactTextString(m) }
func (*SumResponse) ProtoMessage()               {}
func (*SumResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *SumResponse) GetResponse() int64 {
	if m != nil {
		return m.Response
	}
	return 0
}

type PrimeNumberRequest struct {
	Num int32 `protobuf:"varint,1,opt,name=num" json:"num,omitempty"`
}

func (m *PrimeNumberRequest) Reset()                    { *m = PrimeNumberRequest{} }
func (m *PrimeNumberRequest) String() string            { return proto.CompactTextString(m) }
func (*PrimeNumberRequest) ProtoMessage()               {}
func (*PrimeNumberRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *PrimeNumberRequest) GetNum() int32 {
	if m != nil {
		return m.Num
	}
	return 0
}

type PrimeNumberResponse struct {
	Num int32 `protobuf:"varint,1,opt,name=num" json:"num,omitempty"`
}

func (m *PrimeNumberResponse) Reset()                    { *m = PrimeNumberResponse{} }
func (m *PrimeNumberResponse) String() string            { return proto.CompactTextString(m) }
func (*PrimeNumberResponse) ProtoMessage()               {}
func (*PrimeNumberResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *PrimeNumberResponse) GetNum() int32 {
	if m != nil {
		return m.Num
	}
	return 0
}

type ComputeAverageRequest struct {
	Num int32 `protobuf:"varint,1,opt,name=num" json:"num,omitempty"`
}

func (m *ComputeAverageRequest) Reset()                    { *m = ComputeAverageRequest{} }
func (m *ComputeAverageRequest) String() string            { return proto.CompactTextString(m) }
func (*ComputeAverageRequest) ProtoMessage()               {}
func (*ComputeAverageRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *ComputeAverageRequest) GetNum() int32 {
	if m != nil {
		return m.Num
	}
	return 0
}

type ComputeAverageResponse struct {
	Average float64 `protobuf:"fixed64,1,opt,name=average" json:"average,omitempty"`
}

func (m *ComputeAverageResponse) Reset()                    { *m = ComputeAverageResponse{} }
func (m *ComputeAverageResponse) String() string            { return proto.CompactTextString(m) }
func (*ComputeAverageResponse) ProtoMessage()               {}
func (*ComputeAverageResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *ComputeAverageResponse) GetAverage() float64 {
	if m != nil {
		return m.Average
	}
	return 0
}

func init() {
	proto.RegisterType((*Request)(nil), "sum.Request")
	proto.RegisterType((*SumRequest)(nil), "sum.SumRequest")
	proto.RegisterType((*SumResponse)(nil), "sum.SumResponse")
	proto.RegisterType((*PrimeNumberRequest)(nil), "sum.PrimeNumberRequest")
	proto.RegisterType((*PrimeNumberResponse)(nil), "sum.PrimeNumberResponse")
	proto.RegisterType((*ComputeAverageRequest)(nil), "sum.ComputeAverageRequest")
	proto.RegisterType((*ComputeAverageResponse)(nil), "sum.ComputeAverageResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for SumService service

type SumServiceClient interface {
	Sum(ctx context.Context, in *SumRequest, opts ...grpc.CallOption) (*SumResponse, error)
	PrimeNumberDecomposition(ctx context.Context, in *PrimeNumberRequest, opts ...grpc.CallOption) (SumService_PrimeNumberDecompositionClient, error)
	ComputeAverage(ctx context.Context, opts ...grpc.CallOption) (SumService_ComputeAverageClient, error)
}

type sumServiceClient struct {
	cc *grpc.ClientConn
}

func NewSumServiceClient(cc *grpc.ClientConn) SumServiceClient {
	return &sumServiceClient{cc}
}

func (c *sumServiceClient) Sum(ctx context.Context, in *SumRequest, opts ...grpc.CallOption) (*SumResponse, error) {
	out := new(SumResponse)
	err := grpc.Invoke(ctx, "/sum.SumService/Sum", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sumServiceClient) PrimeNumberDecomposition(ctx context.Context, in *PrimeNumberRequest, opts ...grpc.CallOption) (SumService_PrimeNumberDecompositionClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_SumService_serviceDesc.Streams[0], c.cc, "/sum.SumService/PrimeNumberDecomposition", opts...)
	if err != nil {
		return nil, err
	}
	x := &sumServicePrimeNumberDecompositionClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type SumService_PrimeNumberDecompositionClient interface {
	Recv() (*PrimeNumberResponse, error)
	grpc.ClientStream
}

type sumServicePrimeNumberDecompositionClient struct {
	grpc.ClientStream
}

func (x *sumServicePrimeNumberDecompositionClient) Recv() (*PrimeNumberResponse, error) {
	m := new(PrimeNumberResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *sumServiceClient) ComputeAverage(ctx context.Context, opts ...grpc.CallOption) (SumService_ComputeAverageClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_SumService_serviceDesc.Streams[1], c.cc, "/sum.SumService/ComputeAverage", opts...)
	if err != nil {
		return nil, err
	}
	x := &sumServiceComputeAverageClient{stream}
	return x, nil
}

type SumService_ComputeAverageClient interface {
	Send(*ComputeAverageRequest) error
	CloseAndRecv() (*ComputeAverageResponse, error)
	grpc.ClientStream
}

type sumServiceComputeAverageClient struct {
	grpc.ClientStream
}

func (x *sumServiceComputeAverageClient) Send(m *ComputeAverageRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *sumServiceComputeAverageClient) CloseAndRecv() (*ComputeAverageResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(ComputeAverageResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for SumService service

type SumServiceServer interface {
	Sum(context.Context, *SumRequest) (*SumResponse, error)
	PrimeNumberDecomposition(*PrimeNumberRequest, SumService_PrimeNumberDecompositionServer) error
	ComputeAverage(SumService_ComputeAverageServer) error
}

func RegisterSumServiceServer(s *grpc.Server, srv SumServiceServer) {
	s.RegisterService(&_SumService_serviceDesc, srv)
}

func _SumService_Sum_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SumRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SumServiceServer).Sum(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sum.SumService/Sum",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SumServiceServer).Sum(ctx, req.(*SumRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SumService_PrimeNumberDecomposition_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(PrimeNumberRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SumServiceServer).PrimeNumberDecomposition(m, &sumServicePrimeNumberDecompositionServer{stream})
}

type SumService_PrimeNumberDecompositionServer interface {
	Send(*PrimeNumberResponse) error
	grpc.ServerStream
}

type sumServicePrimeNumberDecompositionServer struct {
	grpc.ServerStream
}

func (x *sumServicePrimeNumberDecompositionServer) Send(m *PrimeNumberResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _SumService_ComputeAverage_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(SumServiceServer).ComputeAverage(&sumServiceComputeAverageServer{stream})
}

type SumService_ComputeAverageServer interface {
	SendAndClose(*ComputeAverageResponse) error
	Recv() (*ComputeAverageRequest, error)
	grpc.ServerStream
}

type sumServiceComputeAverageServer struct {
	grpc.ServerStream
}

func (x *sumServiceComputeAverageServer) SendAndClose(m *ComputeAverageResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *sumServiceComputeAverageServer) Recv() (*ComputeAverageRequest, error) {
	m := new(ComputeAverageRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _SumService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "sum.SumService",
	HandlerType: (*SumServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Sum",
			Handler:    _SumService_Sum_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "PrimeNumberDecomposition",
			Handler:       _SumService_PrimeNumberDecomposition_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "ComputeAverage",
			Handler:       _SumService_ComputeAverage_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "sum.proto",
}

func init() { proto.RegisterFile("sum.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 300 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x92, 0x61, 0x4a, 0xc3, 0x40,
	0x10, 0x85, 0x5d, 0x83, 0x56, 0xa7, 0x55, 0xcb, 0x88, 0x1a, 0x22, 0x88, 0x46, 0xd0, 0x56, 0xa4,
	0x48, 0x3d, 0x81, 0xe8, 0x5f, 0xc5, 0x26, 0x07, 0x90, 0x36, 0x8e, 0x92, 0x1f, 0x9b, 0x4d, 0x77,
	0xb3, 0x3d, 0xac, 0xa7, 0x91, 0x4c, 0x76, 0xad, 0x35, 0xf5, 0xdf, 0xce, 0x7b, 0x1f, 0x6f, 0x32,
	0x8f, 0xc0, 0xae, 0xb1, 0x72, 0x54, 0x6a, 0x55, 0x29, 0x0c, 0x8c, 0x95, 0xf1, 0x04, 0x3a, 0x09,
	0xcd, 0x2d, 0x99, 0x0a, 0x2f, 0xa0, 0xf7, 0x91, 0x6b, 0x53, 0xbd, 0x15, 0x56, 0xce, 0x48, 0x87,
	0xe2, 0x5c, 0x0c, 0x82, 0xa4, 0xcb, 0xda, 0x0b, 0x4b, 0x78, 0x09, 0x7b, 0x86, 0x32, 0x55, 0xbc,
	0x7b, 0x66, 0x93, 0x99, 0x5e, 0x23, 0x36, 0x50, 0x7c, 0x0b, 0x90, 0x5a, 0xe9, 0x53, 0xcf, 0x20,
	0xd0, 0x34, 0xe7, 0xb0, 0xee, 0xb8, 0x37, 0xaa, 0xd7, 0x3b, 0x2b, 0xa9, 0x8d, 0x78, 0x08, 0x5d,
	0xa6, 0x4d, 0xa9, 0x0a, 0x43, 0x18, 0xc1, 0x8e, 0x76, 0x6f, 0xf7, 0x01, 0x3f, 0x73, 0x7c, 0x05,
	0xf8, 0xaa, 0x73, 0x49, 0xcd, 0x1e, 0xbf, 0xa0, 0x0f, 0x41, 0x61, 0x25, 0xc3, 0x5b, 0x49, 0xfd,
	0x8c, 0xaf, 0xe1, 0x70, 0x85, 0x73, 0xd1, 0x6d, 0x70, 0x08, 0x47, 0x8f, 0x4a, 0x96, 0xb6, 0xa2,
	0x87, 0x05, 0xe9, 0xe9, 0x27, 0xfd, 0x9f, 0x39, 0x86, 0xe3, 0xbf, 0xa8, 0x8b, 0x0d, 0xa1, 0x33,
	0x6d, 0x24, 0xe6, 0x45, 0xe2, 0xc7, 0xf1, 0x97, 0xe0, 0x26, 0x52, 0xd2, 0x8b, 0x3c, 0x23, 0xbc,
	0x81, 0x20, 0xb5, 0x12, 0x0f, 0xb8, 0x83, 0x65, 0x43, 0x51, 0x7f, 0x29, 0xb8, 0x43, 0x37, 0x70,
	0x02, 0xe1, 0xaf, 0x13, 0x9e, 0x28, 0x53, 0xb2, 0x54, 0x26, 0xaf, 0x72, 0x55, 0xe0, 0x09, 0xf3,
	0xed, 0x26, 0xa2, 0xb0, 0x6d, 0xf8, 0xc0, 0x3b, 0x81, 0xcf, 0xb0, 0xbf, 0x7a, 0x01, 0x46, 0xcc,
	0xaf, 0x6d, 0x20, 0x3a, 0x5d, 0xeb, 0xf9, 0xb8, 0x81, 0x98, 0x6d, 0xf3, 0x4f, 0x74, 0xff, 0x1d,
	0x00, 0x00, 0xff, 0xff, 0xb1, 0xc8, 0x4e, 0x03, 0x51, 0x02, 0x00, 0x00,
}
